app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view() , name='login'),
    path('logout/', auth_views.LogoutView.as_view() , name='logout'),

    path('',views.home,name='home'),

    path('', include('brands.urls')),
    path('categories/', include('categories.urls')),
    path('supplier/', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
    path('', include('bulletins.urls')),
]

brands/models.py
from django.db import models

from django.db import models

class Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

class Projeto(models.Model):
    nome = models.CharField(max_length=200)
    data_inicio = models.DateField()
    historico = models.TextField(blank=True, null=True)
    pessoas = models.ManyToManyField(Pessoa, through='Participacao')

    def __str__(self):
        return self.nome

class Participacao(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    funcao = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.pessoa.nome} - {self.funcao}"
    

class Brand(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name
    

app/templates/components/_ai_result.html
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        SGE Agent - openai 3.5 turbo
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        {{ ai_result|linebreaks }}
      </div>
    </div>
  </div> 
</div>

app/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
    <span class="text-muted dark">© 2024 SGE</span>
  </div>
</footer>

app/templates/components/_header.html
<nav class="navbar navbar-expand-lg navbar-light ">
  <div class="container-fluid mb-2">
    <a class="navbar-brand text-white" href="#">Sistema de Gestão de Estoque (SGE)</a>
  </div>
</nav>

app/templates/components/_pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            Primeira
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Anterior
          </a>
        </li>
      {% endif %}

      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Próxima
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Última
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

app/templates/components/_products_metrics.html
<div class="card mt-4">
    <div class="card-body">
        <div class="row">
            
            <div class="col-md-3">
                <div class="card bg-primary">
                    <div class="card-body">
                        <h7 class="card-title">Quantidade de Produtos</h7>
                        <p class="card-text text-white font-weigth-bold display-7">{{product_metrics.total_quantity}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-danger">
                    <div class="card-body">
                        <h7 class="card-title">Custo de Estoque</h7>
                        <p class="card-text text-white font-weigth-bold display-7">R$ {{product_metrics.total_cost_price}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-success">
                    <div class="card-body">
                        <h7 class="card-title">Valor de Estoque</h7>
                        <p class="card-text text-white font-weigth-bold display-7">R$ {{product_metrics.total_selling_price}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-warning">
                    <div class="card-body">
                        <h7 class="card-title text-black">Lucro de Estoque</h7>
                        <p class="card-text text-black font-weigth-bold display-7">R$ {{product_metrics.total_profit}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/components/_sales_metrics.html
<div class="card mt-4">
    <div class="card-body">
        <div class="row">
            
            <div class="col-md-3">
                <div class="card bg-primary">
                    <div class="card-body">
                        <h7 class="card-title">Quantidade de Vendas</h7>
                        <p class="card-text text-white font-weigth-bold display-7">{{sales_metrics.total_sales}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-danger">
                    <div class="card-body">
                        <h7 class="card-title">Produtos Vendidos</h7>
                        <p class="card-text text-white font-weigth-bold display-7">{{sales_metrics.total_products_sold}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-success">
                    <div class="card-body">
                        <h7 class="card-title">Valor das Vendas</h7>
                        <p class="card-text text-white font-weigth-bold display-7">R$ {{sales_metrics.total_sales_value}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-warning">
                    <div class="card-body">
                        <h7 class="card-title text-black">Lucro das Vendas</h7>
                        <p class="card-text text-black font-weigth-bold display-7">R$ {{sales_metrics.total_sales_profit}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/components/_sidebar.html
<div class="row flex-nowrap">
  <div class="col-auto col-md-0 col-xl-0 px-0 ">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-2 pt-0 text-white">
      <button class="btn btn-dark d-block d-sm-none mb-3" type="button" data-bs-toggle="collapse"
        data-bs-target="#menuCollapse" aria-expanded="false" aria-controls="menuCollapse">
        <i class="bi bi-list fs-4"></i>
      </button>
      <div class="collapse d-sm-block" id="menuCollapse">
        <ul class="nav flex-column align-items-start" id="menu">
          <li>
            <a href="{% url 'home' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-speedometer2 fs-4"></i>
              <span class="ms-1">Dashboard</span>
            </a>
          </li>
          <li>
            <a href="{% url 'bulletin_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-file-text fs-4"></i>
              <span class="ms-1">Boletins</span>
            </a>
          </li>
          {% if perms.suppliers.view_supplier %}
            <li>
              <a href="{% url 'supplier_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-truck fs-4"></i>
                <span class="ms-1">Fornecedores</span>
              </a>
            </li>
          {% endif %}
          {% if perms.brands.view_brand %}
            <li>
              <a href="{% url 'brands_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-shop fs-4"></i>
                <span class="ms-1">Marcas</span>
              </a>
            </li>
          {% endif %}
          <li>
            <a href="{% url 'category_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-tags fs-4"></i>
              <span class="ms-1">Categorias</span>
            </a>
          </li>
          <li>
            <a href="{% url 'product_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-box-seam fs-4"></i>
              <span class="ms-1">Produtos</span>
            </a>
          </li>
          <li>
            <a href="{% url 'inflow_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-arrow-down-left-square fs-4"></i>
              <span class="ms-1">Entradas</span>
            </a>
          </li>
          <li>
            <a href="{% url 'outflow_list' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-arrow-up-right-square fs-4"></i>
              <span class="ms-1">Saídas</span>
            </a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <form action="{% url 'logout' %}" method="post" id="logout-form" class="nav-link px-0 align-middle">
                {% csrf_token %}
                <button type="submit" class="btn btn-link text-decoration-none text-reset nav-link px-0 align-middle">
                  <i class="bi bi-box-arrow-right fs-4 align-middle"></i>
                  <span class="ms-1 align-middle">Sair</span>
                </button>
              </form>
            {% endif %}
          </li>
        </ul>
      </div>
      <hr>
    </div>
  </div>