app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view() , name='login'),
    path('logout/', auth_views.LogoutView.as_view() , name='logout'),

    path('',views.home,name='home'),

    path('', include('brands.urls')),
    path('categories/', include('categories.urls')),
    path('supplier/', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
    path('', include('bulletins.urls')),
]

bulletins/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('bulletins/create/', views.criar_boletim, name='criar_boletim'),
    path('bulletins/create/', views.BulletinCreateView.as_view(), name='criar_boletim'),

    path('bulletins/list/', views.BulletinListView.as_view(), name='bulletin_list'),
    path('bulletins/<int:pk>/detail/', views.BulletinDetailView.as_view(), name='bulletin_detail'),
    
    path('boletim/<int:pk>/pdf/', views.BulletinPDFView.as_view(), name='bulletin_pdf'),

    path('bulletins/<int:pk>/update/', views.BulletinUpdateView.as_view(), name='bulletin_update'),
    path('bulletins/<int:pk>/delete/', views.BulletinDeleteView.as_view(), name='bulletin_delete'),

    path('buscar-envolvido/', views.buscar_envolvido_por_cpf, name='buscar_envolvido'),
]

bulletins/models.py
from django.db import models

class Boletim(models.Model):    
    data_hora_inicio = models.DateTimeField(blank=True, null=True)
    data_hora_termino = models.DateTimeField(blank=True, null=True)
    numero_bi = models.CharField(max_length=30)
    numero_bo = models.CharField(blank=True, null=True, max_length=30)
    classificacao = models.CharField(blank=True, null=True, max_length=100)
    destinatario = models.CharField(blank=True, null=True, max_length=255)
    historico = models.TextField(blank=True, null=True)
    relatornome = models.CharField(blank=True, null=True, max_length=255)
    relatordocumento = models.CharField(blank=True, null=True, max_length=50)
    destinatario = models.CharField(blank=True, null=True, max_length=255)
    autoridadenome = models.CharField(blank=True, null=True, max_length=255)
    autoridadedocumento = models.CharField(blank=True, null=True, max_length=50)
    endereco_dofato = models.CharField(blank=True, null=True, max_length=255)
    numero_dofato = models.CharField(blank=True, null=True, max_length=20)
    bairro_dofato = models.CharField(blank=True, null=True, max_length=100)
    orgao = models.CharField(blank=True, null=True, max_length=100)
    secao = models.CharField(blank=True, null=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"BO {self.numero_bo} - BI {self.numero_bi}"


class Envolvido(models.Model):
    nome = models.CharField(max_length=255)
    naturalidade = models.CharField(blank=True, null=True, max_length=100)
    datanascimento = models.DateField(blank=True, null=True)
    endereco = models.CharField(blank=True, null=True, max_length=255)
    numero = models.CharField(blank=True, null=True, max_length=20)
    bairro = models.CharField(blank=True, null=True, max_length=100)
    cidade = models.CharField(blank=True, null=True, max_length=100)
    uf = models.CharField(blank=True, null=True, max_length=2)
    cep = models.CharField(blank=True, null=True, max_length=10)
    telefone = models.CharField(blank=True, null=True, max_length=20)
    estadocivil = models.CharField(blank=True, null=True, max_length=50)
    cpf = models.CharField(blank=True, null=True, max_length=14)
    identidade = models.CharField(blank=True, null=True, max_length=20)
    profissao = models.CharField(blank=True, null=True, max_length=100)
    email = models.EmailField(blank=True, null=True, )
    escolaridade = models.CharField(blank=True, null=True, max_length=100)

    def __str__(self):
        return self.nome


class BoletimEnvolvimento(models.Model):
    TIPOS_ENVOLVIMENTO = [
        ('SOLICITANTE', 'Solicitante'),
        ('VITIMA', 'Vítima'),
        ('AUTOR', 'Autor'),
        ('TESTEMUNHA', 'Testemunha'),
        ('SOLICITANTE_VITIMA', 'Solicitante/Vítima'),
        ('SOLICITANTE_AUTOR', 'Solicitante/Autor'),
        ('SOLICITANTE_TESTEMUNHA', 'Solicitante/Testemunha'),
    ]

    boletim = models.ForeignKey(Boletim, on_delete=models.CASCADE)
    envolvido = models.ForeignKey(Envolvido, on_delete=models.CASCADE)
    tipo_envolvimento = models.CharField(max_length=30, choices=TIPOS_ENVOLVIMENTO)

    def __str__(self):
        return f"{self.envolvido.nome} ({self.get_tipo_envolvimento_display()})"

bulletins/views.py
from django.shortcuts import render, redirect
from .models import Boletim, BoletimEnvolvimento, Envolvido
from .forms import BoletimForm, BoletimEnvolvimentoForm, BoletimEnvolvimentoFormSet
from django.forms import inlineformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DeleteView, DetailView, UpdateView, CreateView
from django.urls import reverse_lazy

from django.template.loader import get_template
from django.http import HttpResponse
from xhtml2pdf import pisa
from io import BytesIO
from django.views import View

# usado pra pegar caminho da pasta static pra usar no pdf
from django.shortcuts import render
from django.contrib.staticfiles import finders

from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

class BulletinListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Boletim
    template_name = 'bulletin_list.html'
    context_object_name = 'bulletins'
    paginate_by = 10
    permission_required = 'bulletins.view_boletim'

    def get_queryset(self):
        queryset = super().get_queryset()
        filtro_nome_envolvido = self.request.GET.get('filtro_nome_envolvido')
        filtro_endereco_envolvido = self.request.GET.get('filtro_endereco_envolvido')
        filtro_numero_bi = self.request.GET.get('filtro_numero_bi')
        filtro_endereco_bo = self.request.GET.get('filtro_endereco_bo')
        filtro_bairro_bo = self.request.GET.get('filtro_bairro_bo')
        filtro_secao = self.request.GET.get('filtro_secao')
        filtro_cpf = self.request.GET.get('filtro_cpf')
        filtro_nome_relator = self.request.GET.get('filtro_nome_relator')
        filtro_documento_relator = self.request.GET.get('filtro_documento_relator')
        filtro_destinatario = self.request.GET.get('filtro_destinatario')

        if filtro_numero_bi:
            queryset = queryset.filter(numero_bi__icontains=filtro_numero_bi)

        if filtro_nome_envolvido:
            queryset = queryset.filter(boletimenvolvimento__envolvido__nome__icontains=filtro_nome_envolvido)
              
        if filtro_endereco_envolvido:
            queryset = queryset.filter(boletimenvolvimento__envolvido__endereco__icontains=filtro_endereco_envolvido)

        if filtro_endereco_bo:
            queryset = queryset.filter(endereco_dofato__icontains=filtro_endereco_bo)
        
        if filtro_bairro_bo:
            queryset = queryset.filter(bairro_dofato__icontains=filtro_bairro_bo)
        
        if filtro_secao:
            queryset = queryset.filter(secao__icontains=filtro_secao)

        if filtro_cpf:
            filtro_cpf=filtro_cpf.strip().replace('.', '').replace('-', '')
            queryset = queryset.filter(boletimenvolvimento__envolvido__cpf__icontains=filtro_cpf)
             
        if filtro_nome_relator:
            queryset = queryset.filter(relatornome__icontains=filtro_nome_relator)
       
        if filtro_documento_relator:
            queryset = queryset.filter(relatordocumento__icontains=filtro_documento_relator)
        
        if filtro_destinatario:
            queryset = queryset.filter(destinatario__icontains=filtro_destinatario)

        return queryset

class BulletinDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Boletim
    template_name = 'bulletin_delete.html' 
    success_url = reverse_lazy('bulletin_list')
    permission_required = 'bulletins.delete_boletim'

class BulletinDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Boletim
    context_object_name = 'bulletin'
    template_name = 'bulletin_detail.html'
    permission_required = 'bulletins.view_boletim'

    def get_queryset(self):
        # Otimiza a busca para carregar os envolvidos e o envolvimento de uma só vez
        return super().get_queryset().prefetch_related('boletimenvolvimento_set__envolvido')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # O objeto do boletim já tem os envolvidos carregados
        context['envolvimentos'] = self.object.boletimenvolvimento_set.all()
        return context
   
class BulletinUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Boletim
    form_class = BoletimForm
    template_name = 'bulletin_update.html'
    context_object_name = 'bulletin'
    permission_required = 'bulletins.change_boletim'

    # def get_queryset(self):
    #     # Otimiza a busca para carregar os envolvidos e o envolvimento de uma só vez
    #     return super().get_queryset().prefetch_related('boletimenvolvimento_set__envolvido')

    def get_success_url(self):
        return reverse_lazy('bulletin_list')
        # return reverse_lazy('bulletin_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            print('post')
            context['envolvimentos'] = BoletimEnvolvimentoFormSet(self.request.POST, instance=self.object)
            print('post post')
        else:
            context['envolvimentos'] = BoletimEnvolvimentoFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        envolvimento_formset = context['envolvimentos']
        if form.is_valid() and envolvimento_formset.is_valid():
            self.object = form.save()

            envolvimentos = envolvimento_formset.save(commit=True)
            for envolvimento in envolvimentos:
                if envolvimento is not None:
                    # Atualiza/Salva o envolvido explicitamente ANTES
                    if envolvimento.envolvido:
                        envolvido = envolvimento.envolvido
                        # Atualize os campos do envolvido com os dados do formulário
                        form_for_envolvido = next(
                            (f for f in envolvimento_formset.forms if f.instance == envolvimento), None
                        )
                        if form_for_envolvido:
                            # Campos do envolvido no form customizado são 'envolvido_nome', etc
                            envolvido.nome = form_for_envolvido.cleaned_data.get('envolvido_nome', envolvido.nome)
                            envolvido.naturalidade = form_for_envolvido.cleaned_data.get('envolvido_naturalidade', envolvido.naturalidade)
                            envolvido.datanascimento = form_for_envolvido.cleaned_data.get('envolvido_datanascimento', envolvido.datanascimento)
                            envolvido.endereco = form_for_envolvido.cleaned_data.get('envolvido_endereco', envolvido.endereco)
                            envolvido.numero = form_for_envolvido.cleaned_data.get('envolvido_numero', envolvido.numero)
                            envolvido.bairro = form_for_envolvido.cleaned_data.get('envolvido_bairro', envolvido.bairro)
                            envolvido.cidade = form_for_envolvido.cleaned_data.get('envolvido_cidade', envolvido.cidade)
                            envolvido.uf = form_for_envolvido.cleaned_data.get('envolvido_uf', envolvido.uf)
                            envolvido.cep = form_for_envolvido.cleaned_data.get('envolvido_cep', envolvido.cep)
                            envolvido.telefone = form_for_envolvido.cleaned_data.get('envolvido_telefone', envolvido.telefone)
                            envolvido.estadocivil = form_for_envolvido.cleaned_data.get('envolvido_estadocivil', envolvido.estadocivil)
                            envolvido.cpf = form_for_envolvido.cleaned_data.get('envolvido_cpf', envolvido.cpf)
                            envolvido.identidade = form_for_envolvido.cleaned_data.get('envolvido_identidade', envolvido.identidade)
                            envolvido.profissao = form_for_envolvido.cleaned_data.get('envolvido_profissao', envolvido.profissao)
                            envolvido.email = form_for_envolvido.cleaned_data.get('envolvido_email', envolvido.email)
                            envolvido.escolaridade = form_for_envolvido.cleaned_data.get('envolvido_escolaridade', envolvido.escolaridade)
                            envolvido.save()

                    # Define a relação com o boletim e salva o BoletimEnvolvimento
                    envolvimento.boletim = self.object
                    envolvimento.save()

            # Deleta os marcados para exclusão
            for obj in envolvimento_formset.deleted_objects:
                obj.delete()

            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))
    
    def form_valid_old(self, form):
        print('ooooooooooooooooooooooooooooooooooooooo')
        context = self.get_context_data()
        envolvimento_formset = context['envolvimentos']
        if form.is_valid():
            if envolvimento_formset.is_valid():
                # Salva o boletim
                print('envolvimento_formset esta valido')
                self.object = form.save()            
                # Salva os envolvidos
                envolvimentos = envolvimento_formset.save(commit=False)
                for envolvimento in envolvimentos:
                    if envolvimento is not None:
                        envolvimento.boletim = self.object
                        envolvimento.save()
               
                # Não chame save_m2m aqui, pois não há campos ManyToMany
                # envolvimento_formset.save_m2m()
                # Salva os objetos marcados para exclusão, se houver
                for obj in envolvimento_formset.deleted_objects:
                    obj.delete()

                return redirect(self.get_success_url())
            else:

bulletins/templates/bulletin_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Deletar Boletim</h3>

    <div class="card">
        <div class="card-body">
            <p class="card-text">Tem certeza de que deseja excluir o Boletim? <strong>{{ object.name }}</strong></p>
            <form method="post" class="form">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Deletar</button>
            </form>
        </div>
    </div>
    <a href="{% url 'bulletin_list' %}" class="btn btn-secondary mt-3">Voltar para lista de Boletins</a>
</div>

{% endblock %}

bulletins/templates/bulletin_list.html
{% extends 'base.html' %}

{% block title %}
SGE - Boletins
{% endblock %}

{% block content %}

    <div class="row mb-3">
        <div class="col-md-8">
            <form method="get" action="{% url 'bulletin_list' %}">
                <div class="row">
                    <div class="col-md-12">
                        <div class="input-group">
                            <input type="text" class="form-control form-control-sm" name="filtro_nome_envolvido" placeholder="Nome do envolvido" value="{{ request.GET.filtro_nome_envolvido}}">              
                            <input type="text" class="form-control form-control-sm" name="filtro_endereco_envolvido" placeholder="Endereço do envolvido" value="{{ request.GET.filtro_endereco_envolvido}}">              
                        
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="input-group">
                            <input type="text" class="form-control form-control-sm" name="filtro_bairro_bo" placeholder="Bairro do fato" value="{{ request.GET.filtro_bairro_bo}}">              
                            <input type="text" class="form-control form-control-sm" name="filtro_endereco_bo" placeholder="Endereço do fato" value="{{ request.GET.filtro_endereco_bo}}">              
                        
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="input-group">
                            <input type="text" class="form-control form-control-sm" name="filtro_nome_relator" placeholder="Nome do relator" value="{{ request.GET.filtro_nome_relator}}">              
                            <input type="text" class="form-control form-control-sm" name="filtro_documento_relator" placeholder="Documento do relator" value="{{ request.GET.filtro_documento_relator}}">              
                            <input type="text" class="form-control form-control-sm" name="filtro_destinatario" placeholder="Destinatário" value="{{ request.GET.filtro_destinatario}}">              
                        
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="input-group">
                            <input type="text" class="form-control form-control-sm" name="filtro_numero_bi" placeholder="Número do BI" value="{{ request.GET.filtro_numero_bi}}">              
                            <input type="text" class="form-control form-control-sm" name="filtro_secao" placeholder="Seção" value="{{ request.GET.filtro_secao}}">              
                            <input type="text" class="form-control form-control-sm" name="filtro_cpf" placeholder="CPF" value="{{ request.GET.filtro_cpf}}">              
                            <button type="submit" class="btn btn-sm btn-primary">
                                <i class="bi bi-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-4 mt-2 mt-md-0">
            {% if perms.bulletins.add_boletim %}
                <a href="{% url 'criar_boletim' %}" class="btn btn-success float-end">
                    <i class="bi bi-plus">Novo Boletim</i>
                </a>
            {% endif %}
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>BI</th>
                    <th>Data Registro</th>
                    <th>Endereço</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for b in bulletins %} 
                <tr>
                    <td>{{b.numero_bi}}</td>
                    <td>{{b.created_at}}</td>
                    <td>{{b.Endereco}}</td>
                    <td>                    
                        {% if perms.bulletins.view_boletim %}
                            <a href="{% url 'bulletin_detail' b.id %}" class="btn btn-info btn-sm">
                                <i class="bi bi-eye"></i>
                            </a>
                        {% endif %}
                        {% if perms.bulletins.change_boletim %}
                            <a href="{% url 'bulletin_update' b.id %}" class="btn btn-warning btn-sm">
                                <i class="bi bi-pencil"></i>
                            </a>
                        {% endif %}
                        {% if perms.bulletins.delete_boletim %}
                            <a href="{% url 'bulletin_delete' b.id %}" class="btn btn-danger btn-sm">
                                <i class="bi bi-trash"></i>
                            </a>
                        {% endif %} 
                    </td>
                </tr>
                {% endfor %} 
            </tbody>
        </table>
    </div>

    {% include 'components/_pagination.html' %}

{% endblock %}

bulletins/templates/bulletin_pdf.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Boletim de Intervenção</title>
    <style>
        @page {
            size: A4 portrait;
            margin: 1cm;
        }
        body {
            font-family: sans-serif;
            font-size: 8pt;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            
        }
        th, td {
            border: 1px solid #000;
            padding: 2px;
            text-align: left;
            vertical-align: top;
        }
        td {           
            padding-bottom: -3px;           
        }
        th {
            background-color: #e0e0e0;
            
        }
        .header-title {
            text-align: center;
            font-size: 10pt;
            font-weight: bold;
            background-color: white;
        }       
        .section-title {
            background-color: #d0d0d0;
            font-weight: bold;
        }
       
    </style>
</head>
<body>
    <table>
        <thead>
            <tr>
                <td colspan="1" ><img src="{{caminho_local_logo}}"></td>
                <th colspan="11" class="header-title"><br>BOLETIM DE INTERVENÇÃO<br>GUARDA CIVIL MUNICIPAL - CONSELHEIRO LAFAIETE <br></th>
            </tr>
            
        </thead>
        <tbody>
            <tr>
                <td colspan="12" class="section-title">1 - DO FATO</td>
            </tr>
            <tr>
                <td colspan="3"><b>DATA:</b> <br> 14/03/25</td>
                <td colspan="3"><b>NÚMERO BI:</b> <br> {{bulletin.numero_bi}}</td>
                <td colspan="3"><b>NÚMERO BO:</b> <br> {{bulletin.numero_bo}}</td>
                <td colspan="3"><b>CLASSIFICAÇÃO:</b> <br> {{bulletin.classificacao}}171</td>
            </tr>
            <tr>
                <td colspan="5"><b>ENDEREÇO:</b><br>{{bulletin.endereco_dofato}}</td>
                <td colspan="2"><b>NÚMERO:</b><br>{{bulletin.numero_dofato}}</td>
                <td colspan="5"><b>BAIRRO:</b><br> {{bulletin.bairro_dofato}}</td>
            </tr>
            <tr>
                <td colspan="3"><b>ÓRGÃO:</b> <br>{{bulletin.orgao}}</td>
                <td colspan="3"><b>SEÇÃO:</b> <br>{{bulletin.secao}}</td>
                <td colspan="3"><b>DATA/HORA INÍCIO:</b> <br>{{bulletin.data_hora_inicio|date:'d/m/Y H:i'}}</td>
                <td colspan="3"><b>DATA/HORA TÉRMINO:</b> <br>{{bulletin.data_hora_termino|date:'d/m/Y H:i'}}</td>
            </tr>
            <tr>
                <td colspan="12" class="section-title">2 - ENVOLVIDOS</td>
            </tr>
            {% comment %} obs: aqui envolvimentos é uma queryset de envolvimentos e nao um formset {% endcomment %}
            {% for envolvimento in envolvimentos %}
                <tr>
                    <td colspan="12" class="section-title">Envolvido {{forloop.counter}}</td>
                </tr>
                <tr>
                    <td colspan="6"><b>NOME:</b><br>{{envolvimento.envolvido.nome}}</td>
                    <td colspan="3"><b>NATURALIDADE:</b><br>{{envolvimento.envolvido.naturalidade}}</td>
                    <td colspan="3"><b>DATA DE NASCIMENTO:</b><br>{{envolvimento.envolvido.datanascimento|date:'d/m/Y'}}</td>
                </tr>
                <tr>
                    <td colspan="5"><b>ENDEREÇO:</b><br>{{envolvimento.envolvido.endereco}}</td>
                    <td colspan="2"><b>NÚMERO:</b><br>{{envolvimento.envolvido.numero}}</td>
                    <td colspan="5"><b>BAIRRO:</b><br>{{envolvimento.envolvido.bairro}}</td>
                </tr>
                <tr>
                    <td colspan="4"><b>CIDADE:</b> <br>{{envolvimento.envolvido.cidade}}</td>
                    <td colspan="2"><b>UF:</b> <br> {{envolvimento.envolvido.uf}}</td>
                    <td colspan="3"><b>CEP:</b> <br>{{envolvimento.envolvido.cep}}</td>
                    <td colspan="3"><b>TELEFONE:</b> <br> {{envolvimento.envolvido.telefone}}</td>
                </tr>
                <tr>
                    <td colspan="4"><b>ESTADO CIVIL:</b> <br> {{envolvimento.envolvido.estadocivil}}</td>
                    <td colspan="2"><b>CPF:</b> <br>{{envolvimento.envolvido.cpf}}</td>
                    <td colspan="3"><b>IDENTIDADE:</b> <br>{{envolvimento.envolvido.identidade}}</td>
                    <td colspan="3"><b>PROFISSÃO:</b> <br>{{envolvimento.envolvido.profissao}}</td>
                </tr>
                <tr>
                    <td colspan="4"><b>EMAIL:</b><br> {{envolvimento.envolvido.email}}</td>
                    <td colspan="4"><b>TIPO ENVOLVIMENTO:</b><br>{{envolvimento.tipo_envolvimento}}</td>
                    <td colspan="4"><b>ESCOLARIDADE:</b><br>{{envolvimento.envolvido.escolaridade}}</td>
                </tr>
            {% endfor %}
            
            {% comment %} envolvidos vazios apenas pra completar pagina {% endcomment %}
            {% for x in array_envolvidosvazios %}
                <tr>
                    <td colspan="12" class="section-title">Envolvido {{x}}</td>
                </tr>
                <tr>
                    <td colspan="6"><b>NOME:</b><br></td>
                    <td colspan="3"><b>NATURALIDADE:</b><br></td>
                    <td colspan="3"><b>DATA DE NASCIMENTO:</b><br></td>
                </tr>
                <tr>
                    <td colspan="5"><b>ENDEREÇO:</b><br></td>
                    <td colspan="2"><b>NÚMERO:</b><br></td>
                    <td colspan="5"><b>BAIRRO:</b><br></td>
                </tr>
                <tr>
                    <td colspan="4"><b>CIDADE:</b> <br></td>
                    <td colspan="2"><b>UF:</b> <br></td>
                    <td colspan="3"><b>CEP:</b> <br></td>
                    <td colspan="3"><b>TELEFONE:</b> <br></td>
                </tr>
                <tr>
                    <td colspan="4"><b>ESTADO CIVIL:</b> <br></td>
                    <td colspan="2"><b>CPF:</b> <br></td>
                    <td colspan="3"><b>IDENTIDADE:</b> <br></td>
                    <td colspan="3"><b>PROFISSÃO:</b> <br></td>
                </tr>
                <tr>
                    <td colspan="4"><b>EMAIL:</b><br></td>
                    <td colspan="4"><b>TIPO ENVOLVIMENTO:</b><br></td>
                    <td colspan="4"><b>ESCOLARIDADE:</b><br></td>
                </tr>
            {% endfor %}

            <tr>
                <td colspan="12"><b>DESTINATÁRIO:</b><br> {{bulletin.destinatario}}</td>
            </tr>
            <tr>
                <td colspan="12" class="section-title">3 - HISTÓRICO</td>
            </tr>
            <tr>
                <td colspan="12"><b>HISTÓRICO:</b><br> 
                    {{bulletin.historico|linebreaksbr}}  
                    {% for i in linhas_para_loop %}
                        <br>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td colspan="12" class="section-title">4 - RELATOR</td>
            </tr>
            <tr>
                <td colspan="5"><b>NOME:</b><br> {{bulletin.relatornome}}</td>
                <td colspan="3"><b>DOCUMENTO:</b><br> {{bulletin.relatordocumento}}</td>                
                <td colspan="4"><b>RÚBRICA:</b><br> </td>
            </tr>
            <tr>
                <td colspan="12" class="section-title">5 - RECIBO DA AUTORIDADE A QUE SE DESTINA / RESPONSÁVEL REPRESENTANTE</td>
            </tr>
            <tr>
                <td colspan="5"><b>NOME:</b><br>{{bulletin.autoridadenome}}</td>
                <td colspan="3"><b>DOCUMENTO:</b><br> {{bulletin.autoridadedocumento}}</td>
                <td colspan="4"><b>RÚBRICA:</b><br> </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

bulletins/templates/bulletin_sucesso.html
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <title>Sucesso</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-dark text-light">
<div class="container mt-5">
    <h2>Boletim salvo com sucesso!</h2>
    <a href="{% url 'criar_boletim' %}" class="btn btn-outline-light">Cadastrar novo boletim</a>
</div>
</body>
</html>